REM ARQUIVO PARA CARGA EM SGDB TERADATA, UTILIZANDO UTILITÁRIO MULTILOAD PARA UPLOAD DE ARQUIVOS TEXTOS
REM REALIZA UM LOOP FOR QUE LÊ TODOS OS ARQUIVOS TXT COM PREFIXO MSISDN, CHAMANDO O SCRIPT 2 A CADA ITERAÇÃO.

REM DELETA TODOS OS ARQUIVOS DE LOG DE EXECUÇÃO DE BAT E MLOAD
DEL *.log
DEL *.logmload

REM CRIA A PASTA CARREGADO PARA MOVER OS ARQUIVO QUE JA FORAM CARREGADOS
MD .\Carregado

REM SCRIPT DE EXLUSAO DE TODOS OS REGISTROS DA TABELA QUE SERÁ CARREGADA. GERA LOG AO FINAL DA EXECUÇÃO
BTEQ <LIMPA_TAB_HLR.BTQ > LIMPA_TAB_HLR.LOG

REM ESTRUTURA DE REPETICAO PARA PERCORRER TODOS OS ARQUIVOS COM A MASCADA ESPECIFICA A SEREM CARREGADOS
FOR %%I IN (MSISDN_*.txt) DO CALL 02_SCRIPT_MLD_HLR.BAT %%~nxI

EXIT 0